# https://travis-ci.org/HearthSim/twitch-hdt-ebs
language: python
python: "3.6"

env:
  - TOXENV=py36-django21
  - TOXENV=py36-djangomaster
  - TOXENV=flake8
  - TOXENV=mypy

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox

script:
  - tox
