name: Continuous Integration

on: [push]

jobs:
  tox:
    strategy:
      fail-fast: false
      matrix:
        toxenv: [py36-django22, flake8, mypy]
    name: Tox
    runs-on: ubuntu-latest
    env:
      TOXENV: ${{matrix.toxenv}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: tox (${{matrix.toxenv}})
      run: tox
